import { WishlistItem } from "@/types/wishlist";

export const mockWishlist: WishlistItem[] = [
  {
    id: 1,
    name: "Giáo trình C++ cũ",
    price: "45.000đ",
    school: "HUTECH",
    campus: "Ung Văn Khiêm",
    image: "/template.png",
    time: "5 ngày trước",
    imageCount: 2,
    status: "active",
  },
  {
    id: 2,
    name: "Bàn phím cơ Keychron",
    price: "850.000đ",
    school: "FPT Edu",
    campus: "Thủ Đức",
    image: "/template.png",
    time: "1 tuần trước",
    imageCount: 6,
    status: "active",
  },
  {
    id: 3,
    name: "Áo Hoodie Local Brand",
    price: "120.000đ",
    school: "KTX ĐHQG",
    campus: "Khu B",
    image: "/template.png",
    time: "1 tuần trước",
    imageCount: 5,
    status: "sold",
  },
  {
    id: 4,
    name: "Tủ vải đựng quần áo",
    price: "90.000đ",
    school: "UEH",
    campus: "Cơ sở B",
    image: "/template.png",
    time: "1 tuần trước",
    imageCount: 3,
    status: "active",
  },
  {
    id: 5,
    name: "iPhone 13 Pro Max",
    price: "15.500.000đ",
    school: "HUTECH",
    campus: "Thuận An",
    image: "/template.png",
    time: "2 ngày trước",
    imageCount: 4,
    status: "sold",
  },
  {
    id: 6,
    name: "Sách Giải tích 1",
    price: "35.000đ",
    school: "HUTECH",
    campus: "E3 Công nghệ",
    image: "/template.png",
    time: "1 giờ trước",
    imageCount: 1,
    status: "active",
  },
  {
    id: 7,
    name: "Chuột không dây Logitech",
    price: "150.000đ",
    school: "ĐH Công Nghiệp",
    campus: "Gò Vấp",
    image: "/template.png",
    time: "3 giờ trước",
    imageCount: 2,
    status: "active",
  },
  {
    id: 8,
    name: "Quạt sạc mini",
    price: "55.000đ",
    school: "HUTECH",
    campus: "Sài Gòn",
    image: "/template.png",
    time: "6 giờ trước",
    imageCount: 3,
    status: "sold",
  },
  {
    id: 9,
    name: "Bình giữ nhiệt Lock&Lock",
    price: "110.000đ",
    school: "HUTECH",
    campus: "Ung Văn Khiêm",
    image: "/template.png",
    time: "12 giờ trước",
    imageCount: 4,
    status: "active",
  },
  {
    id: 10,
    name: "Macbook Air M1 2020",
    price: "14.500.000đ",
    school: "FPT Edu",
    campus: "Quang Trung",
    image: "/template.png",
    time: "10 ngày trước",
    imageCount: 5,
    status: "sold",
  },
];
